version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DATABASE-NAME=mydatabase
      - DATABASE-USER=myuser
      - DATABASE-PASSWORD=mypassword
      - DATABASE-HOST=db
      - DATABASE-PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
